import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/navbar";
import Header from "../components/header";
import Footer from "../components/footer";
import Content from "../components/content";
import Content1 from "../components/content-1";
import Features from "../components/features";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fuji Edu Mongolia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header>
        <Navbar />
        <Header />
      </header>

      <main>
        <Features />
        {/* <Content1 /> */}
        {/* <Content /> */}
      </main>

      <Footer />
    </>
  );
}
